### PR TITLE
[node] Escape all valid line terminators

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Comment by leobalter** [comment]
The PR # seems accurate for this sort of bug. I'm glad it's being fixed.

**Comment by jugglinmike** [comment]
Thanks, Leo. Note that this will be rendered unnecessary by [the Subsume JSON](https://github.com/tc39/proposal-json-superset) extension slated for ES2019 (thanks, @mathiasbynens!), but this will be necessary to support Node.js until that's shipped.

**Comment by mathiasbynens** [comment]
Kudos to @gibson042 for authoring the proposal in the first place!

**Comment by rwaldron** [comment]
Excellent

**Pull request merged**
