### PR TITLE
Module Support: complete implementation

### PR DESCRIPTION
**Pull request by rwaldron**
- ~~224~~ A whole bunch of tests directly from test262 (count of files that are not _FIXTURE.js)
- Out of the box support: V8, SpiderMonkey, JavaScriptCore and Moddable XS

This is blocked by test262-stream (which just needs to be released)

### CODE REVIEW

**Comment by jugglinmike** [comment]
Here you go, version 1.2.0:

- https://www.npmjs.com/package/test262-stream
- https://github.com/bocoup/test262-stream/tree/v1.2.0

**Comment by rwaldron** [comment]
Fully green with both module and dynamic imports tests. I feel good enough about this to land now.

**Comment by rwaldron** [comment]
I've opened an issue with [ChakraCore](https://github.com/Microsoft/ChakraCore/issues/5274) requesting a new `-module` flag that will enable `ch -module source.js` as a way of executing module code. That issue already has excellent positive momentum!

**Comment by mathiasbynens** [comment]
Is this available through `eshost-cli`?

Note that both V8 and JSC automatically enable the module goal for any files whose name ends with `.mjs` in their shells, without the need to set any command-line flags.

**Comment by rwaldron** [comment]
@mathiasbynens I've just assigned your request to myself.

**Pull request merged**
