### PR TITLE
Add XS test engine

### PR DESCRIPTION
**Pull request by patrick-soquet**
Thank you!

### CODE REVIEW

**Comment by rwaldron** [comment]
Exciting!!

**Comment by rwaldron** [comment]
I should use `${MODDABLE}/build/bin/mac/debug/xst`?

**Comment by bterlson** [comment]
createRealm is not supported was my understanding. @patrick-soquet is that the case? Can we just remove the impl and just `throw new Error("xs does not support createRealm")`?

**Comment by rwaldron** [comment]
I had seen this: https://github.com/Moddable-OpenSource/moddable/blob/public/xs/tools/xst.c#L1019 and assumed it was exposed for use by https://github.com/Moddable-OpenSource/moddable/blob/public/xs/tools/xst.c#L688

**Comment by mathiasbynens** [comment]
Re: https://github.com/bterlson/eshost/pull/49#issuecomment-368964348 [jsvu](https://github.com/GoogleChromeLabs/jsvu) supports installing `xs` now.

```sh
rm -rf -- ~/.jsvu && npm install jsvu -g && jsvu
```

**Comment by patrick-soquet** [comment]
Tell me if there is something more I need to do. Thank you,

**Comment by mathiasbynens** [comment]
@patrick-soquet Have you seen @bterlson’s [comment](https://github.com/bterlson/eshost/pull/49#issuecomment-368967282)?

**Comment by patrick-soquet** [comment]
Yes I did and forgot to reply. Sorry. I fixed it: global.createRealm exists now and is throwing an exception.

**Comment by rwaldron** [comment]
@patrick-soquet thanks for the follow up. I'm going to land this today with the goal of releasing on Monday March 19th

**Pull request merged**
